ALTER TABLE rh_payroll_settings 
ADD COLUMN IF NOT EXISTS time_tracking_method TEXT DEFAULT 'PHYSICAL',
ADD COLUMN IF NOT EXISTS overtime_policy TEXT DEFAULT 'PAID_OVERTIME',
ADD COLUMN IF NOT EXISTS absence_logic JSONB DEFAULT '{}';
